/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Nov 25 03:10:24 GMT 2008 by MyEclipse Hibernate Tool.
 */
package com;

import java.io.Serializable;

/**
 * A class that represents a row in the bookinfo table. 
 * You can customize the behavior of this class by editing the class, {@link Bookinfo()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractBookinfo 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple author property. */
    private java.lang.String author;

    /** The value of the simple price property. */
    private java.lang.Float price;

    /** The value of the simple ms property. */
    private java.lang.String ms;

    /**
     * Simple constructor of AbstractBookinfo instances.
     */
    public AbstractBookinfo()
    {
    }

    /**
     * Constructor of AbstractBookinfo instances given a simple primary key.
     * @param id
     */
    public AbstractBookinfo(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the name column.
     * @return java.lang.String
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the name column.
     * @param name
     */
    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    /**
     * Return the value of the author column.
     * @return java.lang.String
     */
    public java.lang.String getAuthor()
    {
        return this.author;
    }

    /**
     * Set the value of the author column.
     * @param author
     */
    public void setAuthor(java.lang.String author)
    {
        this.author = author;
    }

    /**
     * Return the value of the price column.
     * @return java.lang.Float
     */
    public java.lang.Float getPrice()
    {
        return this.price;
    }

    /**
     * Set the value of the price column.
     * @param price
     */
    public void setPrice(java.lang.Float price)
    {
        this.price = price;
    }

    /**
     * Return the value of the ms column.
     * @return java.lang.String
     */
    public java.lang.String getMs()
    {
        return this.ms;
    }

    /**
     * Set the value of the ms column.
     * @param ms
     */
    public void setMs(java.lang.String ms)
    {
        this.ms = ms;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Bookinfo))
            return false;
        Bookinfo that = (Bookinfo) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
