/*
 * LeapFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.wzm.leap.test;

import com.leapmotion.leap.Controller;

/**
 *
 * @author  __USER__
 */
public class LeapFrame extends javax.swing.JFrame {

	/** Creates new form LeapFrame */
	public LeapFrame() {
		initComponents();
		
		initLeap();
	}

	private void initLeap() {
//		Runnable aa = new Runnable() {
//			
//			@Override
//			public void run() {
//				
//				SampleListener listener = new SampleListener();
//		        Controller controller = new Controller();
//
//		        // Have the sample listener receive events from the controller
//		        controller.addListener(listener);
//				
//			}
//		};
//		
//		new Thread(aa).start();
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("jButton1");

		jButton2.setText("jButton2");

		jButton3.setText("jButton3");

		jButton4.setText("jButton4");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(65, 65,
																		65)
																.addComponent(
																		jButton1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(248,
																		248,
																		248)
																.addComponent(
																		jButton2)))
								.addContainerGap(662, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(463, Short.MAX_VALUE)
								.addComponent(jButton3).addGap(447, 447, 447))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(689, Short.MAX_VALUE)
								.addComponent(jButton4).addGap(221, 221, 221)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(100, 100, 100)
						.addComponent(jButton1).addGap(18, 18, 18)
						.addComponent(jButton2).addGap(102, 102, 102)
						.addComponent(jButton3).addGap(48, 48, 48)
						.addComponent(jButton4)
						.addContainerGap(216, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		Runnable aa = new Runnable() {
//			
			@Override
			public void run() {
				
				SampleListener listener = new SampleListener();
		        Controller controller = new Controller();

		        // Have the sample listener receive events from the controller
		        controller.addListener(listener);
				
			}
		};
		
		Thread t1 = new Thread(aa);
		
		
		t1.setDaemon(true);
		t1.start();
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LeapFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	// End of variables declaration//GEN-END:variables

}