/*
 * TestUI.java
 *
 * Created on __DATE__, __TIME__
 */

package com.wzm.ssq.client;

import java.util.List;

import com.wzm.server.dao.base.BaseDao;
import com.wzm.server.entity.base.BaseEntity;
import com.wzm.server.entity.formula.RedFormulaCaclMulForcast;
import com.wzm.test.BlueFormulaTest;
import com.wzm.test.RedFormulaTest;
import com.wzm.util.ClientBeanUtil;

/**
 * 
 * @author __USER__
 */
public class TestUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6379190003491188718L;

	/** Creates new form TestUI */
	public TestUI() {
		initComponents();
		initValues();
	}

	private void initValues() {
		comboForcastNum.addItem(300);
		comboForcastNum.addItem(400);
		comboForcastNum.setSelectedIndex(0);

		comboSpaceNum.addItem(50);
		comboSpaceNum.addItem(60);
		comboSpaceNum.addItem(80);
		comboSpaceNum.addItem(100);
		comboSpaceNum.setSelectedIndex(0);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jScrollPane1 = new javax.swing.JScrollPane();
jTextArea1 = new javax.swing.JTextArea();
jScrollPane2 = new javax.swing.JScrollPane();
jTextArea2 = new javax.swing.JTextArea();
btnGenerateSql = new javax.swing.JButton();
btnCreateStats = new javax.swing.JButton();
jLabel1 = new javax.swing.JLabel();
comboForcastNum = new javax.swing.JComboBox();
jLabel2 = new javax.swing.JLabel();
comboSpaceNum = new javax.swing.JComboBox();
jLabel3 = new javax.swing.JLabel();
txtCurrentIndex = new javax.swing.JTextField();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jTextArea1.setColumns(20);
jTextArea1.setRows(5);
jTextArea1.setName("txt1");
jScrollPane1.setViewportView(jTextArea1);

jTextArea2.setColumns(20);
jTextArea2.setRows(5);
jTextArea2.setName("txtResult");
jScrollPane2.setViewportView(jTextArea2);

btnGenerateSql.setText("generate");
btnGenerateSql.setName("btnGen");
btnGenerateSql.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnGenerateSqlActionPerformed(evt);
}
});

btnCreateStats.setText("\u751f\u6210\u7edf\u8ba1");
btnCreateStats.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnCreateStatsActionPerformed(evt);
}
});

jLabel1.setText("forcastNum");

//comboForcastNum.setModel(javax.swing.DefaultComboBoxModel@4de38a5b);
comboForcastNum.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
comboForcastNumActionPerformed(evt);
}
});

jLabel2.setText("spaceNum");

//comboSpaceNum.setModel(javax.swing.DefaultComboBoxModel@2e44d4ee);

jLabel3.setText("\u5f53\u524d\u671f");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(76, 76, 76)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(comboForcastNum, 0, 64, Short.MAX_VALUE)
.addGap(131, 131, 131)
.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(comboSpaceNum, 0, 63, Short.MAX_VALUE)
.addGap(147, 147, 147)
.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(txtCurrentIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE))
.addGap(43, 43, 43)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(btnGenerateSql)
.addComponent(btnCreateStats))
.addGap(20, 20, 20))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addContainerGap(63, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
.addComponent(jLabel1)
.addComponent(comboForcastNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel3)
.addComponent(jLabel2)
.addComponent(comboSpaceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txtCurrentIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(51, 51, 51)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(41, 41, 41)
.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addGap(41, 41, 41)
.addComponent(btnGenerateSql)
.addGap(210, 210, 210)
.addComponent(btnCreateStats)))
.addGap(29, 29, 29))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void btnGenerateSqlActionPerformed(java.awt.event.ActionEvent evt) {

		jTextArea2.setText("");
		String tmp = jTextArea1.getText().trim();
		if (tmp.length() == 0) {
			return;
		}
		
		int forcastNum = ((Integer)comboForcastNum.getSelectedItem()).intValue();
		int spaceNum = ((Integer)comboSpaceNum.getSelectedItem()).intValue();
		int currentIndex = Integer.parseInt(txtCurrentIndex.getText().trim());
		
		String[] tmps = tmp.split(",");
		
		String[] str1 = new String[4];
		for(int i=0;i<str1.length;i++) {
			str1[i] = "select  ffromssqindex,ftossqindex \n";
		}
		
		String str2 = "select  ffromssqindex,ftossqindex \n";
		
		for (int i = 0; i < tmps.length; i++) {
			String nums = tmps[i].substring(1);
			str1[0] = str1[0] + ",max(fformula" + nums + "krcount) , min(fformula"
					+ nums + "krcount) \n";
			
			str1[1] = str1[1] + ",max(fformula" + nums + "krcount) , min(fformula"
					+ nums + "krcount) \n";
			
			str1[2] = str1[2] + ",max(fformula" + nums + "krcount) , min(fformula"
					+ nums + "krcount) \n";
			
			str1[3] = str1[3] + ",max(fformula" + nums + "krcount) , min(fformula"
					+ nums + "krcount) \n";
			
			str2 = str2 + ",fformula" + nums + "krcount \n";
		}
		
		BaseDao basedao = (BaseDao)ClientBeanUtil.getDao("baseDao");
		
		String hql = "from RedFormulaCaclMulForcast a where a.forcastSpaceNum = ? " +
				" and a.spaceNum=? and a.toSsqIndex=?";
		List<BaseEntity> list = basedao.find(hql,new Object[]{forcastNum, spaceNum, currentIndex});
		int beginssqindex = ((RedFormulaCaclMulForcast)list.get(0)).getFromSsqIndex();
		
		str1[0] = str1[0] + " from t_redfulcaclmulsts where fspacenum = "+spaceNum+" and ffromssqindex >= "+ 
				beginssqindex+" and ftossqindex <= "+currentIndex+"  order by ftossqindex desc";
		
		str1[1] = str1[1] + " from t_redfulcaclmulsts where fspacenum = "+spaceNum+" and ffromssqindex >= "+ 
				(beginssqindex-1000)+" and ftossqindex <= "+currentIndex+"  order by ftossqindex desc";
		
		str1[2] = str1[2] + " from t_redfulcaclmulsts where fspacenum = "+spaceNum+" and ffromssqindex >= "+ 
				(beginssqindex-2000)+" and ftossqindex <= "+currentIndex+"  order by ftossqindex desc";
		
		str1[3] = str1[3] + " from t_redfulcaclmulsts where fspacenum = "+spaceNum+" and ffromssqindex >= "+ 
				(beginssqindex-3000)+" and ftossqindex <= "+currentIndex+"  order by ftossqindex desc";
		
		str2 = str2 + " from t_redfulcaclmulsts where fspacenum = "+spaceNum+" and ftossqindex="+currentIndex;

		jTextArea2.setText(str2+ ";\n\n" +str1[0] + ";\n\n" + str1[1] + ";\n\n" +str1[2] + ";\n\n" +str1[3] + ";\n\n" );
	}

	private void comboForcastNumActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnCreateStatsActionPerformed(java.awt.event.ActionEvent evt) {
		
		TestUIHelper.buildSSqRecordAndStats();
		
//		new Thread(new Runnable() {
//			
//			@Override
//			public void run() {
//				BlueFormulaTest.buildBlue();
//			}
//		}).start();

//		new Thread(new Runnable() {
//			
//			@Override
//			public void run() {
//				RedFormulaTest.buildRed();
//			}
//		}).start();
		
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TestUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCreateStats;
	private javax.swing.JButton btnGenerateSql;
	private javax.swing.JComboBox comboForcastNum;
	private javax.swing.JComboBox comboSpaceNum;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField txtCurrentIndex;
	// End of variables declaration//GEN-END:variables

}